### ISSUE TITLE
Tratamento de exceção ao atualizar e excluir cliente

### ISSUE THREAD

**Issue by oliveiralex** [TiagoBorborema/Trabalho01BootCamp#1]
Olá Tiago, tudo bem?

O seu projeto referente a tarefa CRUD Cliente (cap. 1) já foi aceito, parabéns! Mas para ficar 100%, favor incluir o tratamento de exceções. Está retornando erro 500 ao atualizar e excluir um cliente quando é informado um id que não existe.

Atenciosamente,
Alexandre Oliveira

**Comment by TiagoBorborema** [comment]
Opa Alexandre, acho q envie antes do commit, eu tinha tratado... Vou
reenviar mais tarde, obrigado.

Em seg, 8 de fev de 2021 11:26, Alexandre <notifications@github.com>
escreveu:

**Comment by oliveiralex** [comment]
Beleza Tiago! Assim que você enviar me fala que eu testo novamente ok?

Abraço

**Comment by TiagoBorborema** [comment]
Alexandre boa noite,

Eu olhei aqui o commit está atualizado e para mim o erro está tratado com
retorno 404. Faz a validação novamente por favor.


*Tiago A. Borborema*




Em seg., 8 de fev. de 2021 às 13:15, Alexandre <notifications@github.com>
escreveu:

**Comment by TiagoBorborema** [comment]
Alexandre boa noite,

Eu olhei aqui o commit está atualizado e para mim o erro está tratado com
retorno 404. Faz a validação novamente por favor.

*Tiago A. Borborema*




Em seg., 8 de fev. de 2021 às 11:26, Alexandre <notifications@github.com>
escreveu:

**Comment by oliveiralex** [comment]
Caro Tiago, apenas baixei o seu projeto novamente utilizando o link (https://github.com/TiagoBorborema/Trabalho01BootCamp) e o erro continua. Seguem as imagens do postman:

PUT: Atualizar cliente inexistente

![Captura de tela de 2021-02-10 18-21-44](https://user-images.githubusercontent.com/2441741/107574013-fdc55300-6bcc-11eb-8b5b-7b43a2564560.png)

DELETE: Remover cliente inexistente

![Captura de tela de 2021-02-10 18-23-10](https://user-images.githubusercontent.com/2441741/107574137-1cc3e500-6bcd-11eb-9d1f-b376bfe88a05.png)

Se você puder compartilhar o link novamente por gentileza.

**Comment by TiagoBorborema** [comment]
A entendi, desculpa eu apliquei o tratamento apenas na consulta por id.
Vou ajustar e aviso novamente.

Em qua, 10 de fev de 2021 18:24, Alexandre <notifications@github.com>
escreveu:

**Comment by oliveiralex** [comment]
Tranquilo Tiago! Bom trabalho e assim que você fizer me dá um toque que eu confiro aqui tá bom?

**Comment by TiagoBorborema** [comment]
Bom dia Alexandre!

Ajuste realizado, pode validar novamente por favor.
*Tiago A. Borborema*




Em qui., 11 de fev. de 2021 às 16:10, Alexandre <notifications@github.com>
escreveu:

**Comment by oliveiralex** [comment]
Tiago, o tratamento de exceção para o PUT está certinho agora! Parabéns.
Porém, o tratamento do DELETE ainda está retornando 500 ao remover um cliente com id inexistente. Acredito que já esteja suficiente, então vou encerrar a issue.

Abraço e bons estudos
